version: 2
jobs:
  helm-package:
    docker:
      - image: 708371444347.dkr.ecr.us-east-1.amazonaws.com/concourse-runner:latest
        aws_auth:
          aws_access_key_id: $OPS_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $OPS_AWS_SECRET_ACCESS_KEY
    environment:
      GIT_SSH_COMMAND: 'ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes'
    steps:
      - run:
          name: "clone airbyte-helm repo"
          command: | 
             git clone git@github.com:datacamp-engineering/airbyte-helm.git
             cd $CIRCLE_PROJECT_REPONAME
      - run:
          name: "helm package airbyte "
          command: | 
             helm package /Users/james.harris/Documents/code/airbyte-helm/airbyte --dependency-update
      - run:
          name: "helm package airbyte "
          command: | 
             helm package /Users/james.harris/Documents/code/airbyte-helm/airbyte-bootloader --dependency-update
      - run:
          name: "helm package airbyte "
          command: | 
             helm package /Users/james.harris/Documents/code/airbyte-helm/airbyte-pod-sweeper --dependency-update
      - run:
          name: "helm package airbyte "
          command: | 
             helm package /Users/james.harris/Documents/code/airbyte-helm/airbyte-server --dependency-update
      - run:
          name: "helm package airbyte "
          command: | 
             helm package /Users/james.harris/Documents/code/airbyte-helm/airbyte-temporal --dependency-update
      - run:
          name: "helm package airbyte "
          command: | 
             helm package /Users/james.harris/Documents/code/airbyte-helm/airbyte-webapp --dependency-update
      - run:
          name: "helm package airbyte "
          command: | 
             helm package /Users/james.harris/Documents/code/airbyte-helm/airbyte-worker --dependency-update
workflows:
  version: 2
  build:
    jobs:
      - helm-package:
          context: org-global
          filters:
            branches:
              only: master
