version: 2.1
jobs:
  helm-package:
    docker:
      - image: 708371444347.dkr.ecr.us-east-1.amazonaws.com/concourse-runner:latest
        aws_auth:
          aws_access_key_id: $OPS_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $OPS_AWS_SECRET_ACCESS_KEY
    environment:
      GIT_SSH_COMMAND: 'ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes'
    steps:
      - run:
          name: "clone airbyte-helm repo"
          command: | 
             git clone git@github.com:datacamp-engineering/airbyte-helm.git
      - run:
          name: "helm package airbyte"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add airbyte-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "helm package airbyte bootloader"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte-bootloader --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add airbyte-bootloader-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "helm package airbyte pod-sweeper"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte-pod-sweeper --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add pod-sweeper-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "helm package airbyte server"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte-server --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add airbyte-server-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "helm package airbyte temporal"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte-temporal --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add airbyte-temporal-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "helm package airbyte webapp"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte-webapp --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add airbyte-webapp-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "helm package airbyte-worker"
          command: | 
             cd ~/project/$CIRCLE_PROJECT_REPONAME
             helm3 package airbyte-worker --dependency-update --version 0.33.${CIRCLE_BUILD_NUM}
             git add airbyte-worker-0.33.${CIRCLE_BUILD_NUM}.tgz
      - run:
          name: "commit new version"
          command: |
             git commit -m "commit new version 0.33.${CIRCLE_BUILD_NUM}"
             git push -u origin master
workflows:
  version: 2
  build:
    jobs:
      - helm-package:
          context: org-global
          filters:
            branches:
              only: master